site_name: PR Mesh
site_url: https://mydomain.org/mysite

theme:
  name: material
  icon:
    logo: material/access-point
  favicon: assets/images/access-point.svg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - palette.toggle
    - navigation.tabs.sticky


nav:
  - Home: index.md
  - Guides: guides.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
